name: github_challenge
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_ui_auth: ^1.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_signin_button: ^2.0.0
  get_it: ^7.2.0
  go_router: ^6.5.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  http: ^0.13.5
  material_design_icons_flutter: ^6.0.7096
  path: ^1.8.2
  rive: ^0.10.3
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/

  fonts:
  - family: Hubot
    fonts:
      - asset: assets/fonts/Hubot-Sans-Light.ttf
        weight: 300
      - asset: assets/fonts/Hubot-Sans-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Hubot-Sans-Regular.ttf
        weight: 400
      - asset: assets/fonts/Hubot-Sans-RegularItalic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Hubot-Sans-Medium.ttf
        weight: 500
      - asset: assets/fonts/Hubot-Sans-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Hubot-Sans-Bold.ttf
        weight: 700
      - asset: assets/fonts/Hubot-Sans-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Hubot-Sans-Black.ttf
        weight: 900
      - asset: assets/fonts/Hubot-Sans-BlackItalic.ttf
        weight: 900
        style: italic